project:
  name: raspberry_pi5
  description: EmbITE MVP validation project for Raspberry Pi 5

dut:
  name: raspberry_pi_5
  platform: raspberry_pi_5

  connection:
    type: ssh
    host: 192.168.29.234
    port: 22
    username: pi
    password_prompt: true

tests:
  - tests/system.tst

reporting:
  enabled: true
  directory: report/runs
